version: "3.8"

services:
  database:
    image: postgres:17
    container_name: snapfood-database-1
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - snapfood_default

volumes:
  pgdata:

networks:
  snapfood_default:

